### ISSUE TITLE
Broken /tst/teststandard/varnames.tst in GAP

### ISSUE THREAD

**Issue by alex-konovalov** [gap-packages/recog#61] opened 2019-05-19 21:05 UTC
See https://api.travis-ci.org/v3/job/534543968/log.txt (the log is very long, diffs are at the very end - a hint what to do to get rid of `perl: warning: Please check that your locale settings:` will be appreciated):
```
########> Diff in /home/gap/inst/gap-master/tst/teststandard/varnames.tst:6
# Input is:
Filtered( NamesSystemGVars(), x -> not x in ALL_KEYWORDS() and
           ( Length(x)=1 or (IsLowerAlphaChar(x[1]) and Length(x) < 12) ) );
# Expected output:
[ "*", "+", "-", ".", "/", "<", "=", "E", "X", "Z", "^", "fail", "infinity", 
  "last", "last2", "last3", "time" ]
# But found:
[ "*", "+", "-", ".", "/", "<", "=", "E", "X", "Z", "^", "fail", "fhmethsel", 
  "forfactor", "forkernel", "gensN", "gensNslp", "infinity", "isequal", 
  "isone", "last", "last2", "last3", "pregensfac", "slptonice", "slptostd", 
  "time" ]
########
```
First, this happens in the fresh build of https://travis-ci.org/gap-infra/gap-docker-master-testsuite today, with packages as on https://github.com/gap-system/gap/wiki/Package-updates-status today (from todays's upload of https://www.gap-system.org/pub/gap/gap4pkgs/packages-master.tar.gz). I am puzzled why this happens only when the test is run when GAP is started with the default selection of packages (see https://travis-ci.org/gap-infra/gap-docker-master-testsuite)

**Comment by alex-konovalov** [comment] 2019-05-19 21:10
I have submitted this here, since the offending variables seem to belong to the recog package - the actual reason might be anywhere else, e.g. if some package have provisions in the case when recog is not available.

**Comment by fingolfin** [comment] 2019-05-19 21:54
That's odd. Nothing has changed in recog recently, and e.g. `forkernel` has been around forever, unchanged. I wonder if this might be related to the "heisenbug" @ChrisJefferson and other recently observed...

**Comment by fingolfin** [comment] 2019-05-19 21:55
Re: the perl warnings, try setting `LANG=C` in the environment.

**Comment by fingolfin** [comment] 2019-05-19 22:07
This is caused by the recent atlasrep update, which now has recog as one of its "suggested" packages (for its test suite). So one workaround would be to only load "required" dependencies, not suggested ones.

The problem should also go away in early July, as one of the things planned for the [Summer School Matrix Group Recognition](https://lbfm-rwth.github.io/Summer-School-MGRP/) is to rename a bunch of things to something more sensible.
But of course we need to fix the GAP test suite until then; we could just disable the offending test temporarily.

**Comment by alex-konovalov** [comment] 2019-05-20 09:08
I still do not have an understanding how this happens. Note that starting GAP and calling
```
Filtered( NamesSystemGVars(), x -> not x in ALL_KEYWORDS() and
           ( Length(x)=1 or (IsLowerAlphaChar(x[1]) and Length(x) < 12) ) ); 
```
shows these variables when GAP is started with default packages, but does not show them when GAP is started with `-A` option, and then either `recog` or `AtlasRep` are loaded.

**Comment by alex-konovalov** [comment] 2019-05-20 14:25
@fingolfin will try - now uses `LANG=en_GB.UTF-8`

**Comment by fingolfin** [comment] 2019-05-20 16:32
Resolved by https://github.com/gap-system/gap/pull/3465 -- the true cause of this (the "bad" names) hopefully will be fixed in July.

**Closed by fingolfin** 2019-05-20 16:32 UTC
